package Ventanas;

import proveeduria_empresa_v3.Producto;
import proveeduria_empresa_v3.Archivos;
import proveeduria_empresa_v3.Kardex;
import proveeduria_empresa_v3.Compras;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author Grupo D, S.I. - 001 
 */
public class AddCompra extends javax.swing.JFrame {

    /**
     * Creates new form AddCompra
     */
    private Calendar c = Calendar.getInstance();
    private String fecha = c.get(Calendar.DATE) + "/" + (c.get(Calendar.MONTH) + 1) + "/" + c.get(Calendar.YEAR);
    public String dirr = "Compras.txt";

    public AddCompra() {
        initComponents();
        setLocationRelativeTo(null);
        gCategoria.setModel(new javax.swing.DefaultComboBoxModel<>((String[]) Archivos.leerFichero("categoria.txt")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gSecuencia = new javax.swing.JTextField();
        gProducto = new javax.swing.JTextField();
        gPrecio = new javax.swing.JTextField();
        gCantidad = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        gCategoria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Compras");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Secuencia:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Producto/Codigo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio unidad:");

        gSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSecuenciaActionPerformed(evt);
            }
        });
        gSecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gSecuenciaKeyTyped(evt);
            }
        });

        gPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPrecioActionPerformed(evt);
            }
        });
        gPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gPrecioKeyTyped(evt);
            }
        });

        gCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gCantidadKeyTyped(evt);
            }
        });

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compartimiento.png"))); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar-el-polvo.png"))); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-atras.png"))); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Categoria");

        gCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loadingmark_87510 (1).png"))); // NOI18N
        jButton1.setText("Abastecer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigo-de-barras.png"))); // NOI18N
        jButton2.setText("Codigos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-supermercado.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-web-de-ayuda.png"))); // NOI18N
        jButton3.setText("AYUDA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(335, 335, 335)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gCategoria, 0, 104, Short.MAX_VALUE)
                                .addComponent(gCantidad)
                                .addComponent(gPrecio)
                                .addComponent(gProducto)
                                .addComponent(gSecuencia)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addComponent(jButton3))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(botonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11)))
                        .addGap(30, 30, 30)
                        .addComponent(gSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(83, 83, 83)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        new VenCompra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void gSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gSecuenciaActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        Compras[] a = (Compras[]) Archivos.leerFichero(dirr);
        boolean key = false;
        for (int i = 0; i < a.length; i++) {
            key = gSecuencia.getText().equals(a[i].getCodSecuencia());
            if (key) {
                JOptionPane.showMessageDialog(null, "El # de Secuencia ya pertenece a una Compra");
                break;
            }
        }
        if (!key) {
            if (!((gSecuencia.getText().equals(""))
                    || (gProducto.getText().equals(""))
                    || (gPrecio.getText().equals(""))
                    || (gCantidad.getText().equals("")))) {
                Producto[] listaProductos = (Producto[]) Archivos.leerFichero("Productos.txt");
                Producto producto;
                Compras nuevo = new Compras(Integer.parseInt(gSecuencia.getText()), fecha, gProducto.getText(),
                        Integer.parseInt(gCantidad.getText()), Double.parseDouble(gPrecio.getText()));
                Kardex[] kardex = (Kardex[]) Archivos.leerFichero("Kardex.txt");
                Kardex registro = new Kardex("C" + gSecuencia.getText(), fecha,
                        Integer.parseInt(gCantidad.getText()), (Double.parseDouble(gPrecio.getText())) * Integer.parseInt(gCantidad.getText()), "Ingreso");
                producto = new Producto("" + listaProductos.length, gProducto.getText(), gCategoria.getSelectedItem().toString(),
                        Double.parseDouble(gPrecio.getText()), Integer.parseInt(gCantidad.getText()));
                Archivos.escribirFichero("Productos.txt", Producto.agregarProductos(listaProductos, producto));
                Archivos.escribirFichero(dirr, Compras.agregarCompras(a, nuevo));
                Archivos.escribirFichero("Kardex.txt", Kardex.agregarKardex(kardex, registro));

                JOptionPane.showMessageDialog(null, "AGREGADO CON ÉXITO!");
            } else {
                JOptionPane.showMessageDialog(null, "CAMPOS VACIOS!");
            }
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        gProducto.setText("");
        gSecuencia.setText("");
        gPrecio.setText("");
        gCantidad.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        Compras[] a = (Compras[]) Archivos.leerFichero(dirr);
        boolean key = gSecuencia.getText().equals("");
        Compras nuevo = Compras.buscarCompras(a, (key) ? 0 : Integer.parseInt(gSecuencia.getText()));
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "Compra NO ENCONTRADA");
        } else {
            gProducto.setText(nuevo.getProdAdquiridos());
            gSecuencia.setText("" + nuevo.getCodSecuencia());
            gPrecio.setText("" + nuevo.getPrecioUnit());
            gCantidad.setText("" + nuevo.getCantProductos());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        Compras[] a = (Compras[]) Archivos.leerFichero(dirr);
        boolean key = gSecuencia.getText().equals("");
        Compras nuevo = Compras.buscarCompras(a, (key) ? 0 : Integer.parseInt(gSecuencia.getText()));
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "COMPRA A ELIMINAR NO EXISTE");
        } else {
            Compras[] b = Compras.eliminarCompras(a, Integer.parseInt(gSecuencia.getText()));
            Archivos.escribirFichero(dirr, b);
            JOptionPane.showMessageDialog(null, "ELIMINADO CON ÉXITO!");
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void gSecuenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gSecuenciaKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gSecuencia.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gSecuenciaKeyTyped

    private void gCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gCantidadKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gCantidad.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gCantidadKeyTyped

    private void gPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gPrecioKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if ((key < '0' || key > '9') && (key != '.')) {
            evt.consume();
        }
        if (gPrecio.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gPrecioKeyTyped

    private void gPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Compras[] a = (Compras[]) Archivos.leerFichero(dirr);
        boolean key = false;
        for (int i = 0; i < a.length; i++) {
            key = gSecuencia.getText().equals(a[i].getCodSecuencia());
            if (key) {
                JOptionPane.showMessageDialog(null, "El # de Secuencia ya pertenece a una Compra");
                break;
            }
        }
        if (!key) {
            if (!((gSecuencia.getText().equals(""))
                    || (gProducto.getText().equals(""))
                    || (gPrecio.getText().equals(""))
                    || (gCantidad.getText().equals("")))) {
                Producto[] listaProductos = (Producto[]) Archivos.leerFichero("Productos.txt");
                Producto producto = Producto.buscarProductos(listaProductos, gProducto.getText());
                Compras nuevo = new Compras(Integer.parseInt(gSecuencia.getText()), fecha, gProducto.getText(),
                        Integer.parseInt(gCantidad.getText()), Double.parseDouble(gPrecio.getText()));
                Kardex[] kardex = (Kardex[]) Archivos.leerFichero("Kardex.txt");
                Kardex registro = new Kardex("C" + gSecuencia.getText(), fecha,
                        Integer.parseInt(gCantidad.getText()), producto.getPrecio() * Integer.parseInt(gCantidad.getText()), "Ingreso");
                producto.setStock(producto.getStock() + Integer.parseInt(gCantidad.getText()));
                producto.setPrecio(Double.parseDouble(gPrecio.getText()));
                Archivos.escribirFichero("Productos.txt", Producto.actualizarProductos(listaProductos, producto));
                Archivos.escribirFichero("Kardex.txt", Kardex.agregarKardex(kardex, registro));
                nuevo.setProdAdquiridos(producto.getNombre());
                Archivos.escribirFichero(dirr, Compras.agregarCompras(a, nuevo));
                JOptionPane.showMessageDialog(null, "AGREGADO CON ÉXITO");
            } else {
                JOptionPane.showMessageDialog(null, "CAMPOS VACIOS!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new VenProductosCodigos().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Ayuda a = new Ayuda();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField gCantidad;
    private javax.swing.JComboBox<String> gCategoria;
    private javax.swing.JTextField gPrecio;
    private javax.swing.JTextField gProducto;
    private javax.swing.JTextField gSecuencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
