package Ventanas;

import javax.swing.JOptionPane;
import proveeduria_empresa_v3.Empleado;
import proveeduria_empresa_v3.Archivos;
/**
 *
 * @author Grupo D, S.I. - 001 
 */
public class AddEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form AddEmpleado
     */
    public String dirr = "Empleado.txt";

    public AddEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gCodigoID = new javax.swing.JTextField();
        gIdentificacion = new javax.swing.JTextField();
        gNombre = new javax.swing.JTextField();
        gDireccion = new javax.swing.JTextField();
        gTelefono = new javax.swing.JTextField();
        gSueldo = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Empleado");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Codigo ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Dirección:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sueldo:");

        gCodigoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCodigoIDActionPerformed(evt);
            }
        });
        gCodigoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gCodigoIDKeyTyped(evt);
            }
        });

        gIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gIdentificacionKeyTyped(evt);
            }
        });

        gNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gNombreKeyTyped(evt);
            }
        });

        gDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDireccionActionPerformed(evt);
            }
        });

        gTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gTelefonoKeyTyped(evt);
            }
        });

        gSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gSueldoKeyTyped(evt);
            }
        });

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compartimiento.png"))); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar-el-polvo.png"))); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-atras.png"))); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(gSueldo)
                                .addComponent(gTelefono))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonAtras)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)))
                                    .addGap(90, 90, 90)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gCodigoID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(gIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gCodigoID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gCodigoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCodigoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gCodigoIDActionPerformed

    private void gDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gDireccionActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        Empleado[] a = (Empleado[]) Archivos.leerFichero(dirr);
        Empleado nuevo = Empleado.buscarEmpleado(a, gCodigoID.getText());
        if (nuevo == null) {

            JOptionPane.showMessageDialog(null, "Empleado NO encontrado");
        } else {
            if (!((gCodigoID.getText().equals(""))
                    || (gIdentificacion.getText().equals(""))
                    || (gNombre.getText().equals(""))
                    || (gDireccion.getText().equals(""))
                    || (gTelefono.getText().equals(""))
                    || (gSueldo.getText().equals("")))) {
                Empleado[] b = Empleado.eliminarEmpleado(a, gCodigoID.getText());
                Empleado[] c = Empleado.agregarEmpleado(b,
                        new Empleado(gCodigoID.getText(), gIdentificacion.getText(), gNombre.getText(), gDireccion.getText(), gTelefono.getText(),
                                Double.parseDouble(gSueldo.getText())));
                Archivos.escribirFichero(dirr, c);
                JOptionPane.showMessageDialog(null, "ACTUALIZADO CON ÉXITO!");
            } else {
                JOptionPane.showMessageDialog(null, "CAMPOS VACIOS, NO se puede Actualizar");
            }
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        new VenEmpleado().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        Empleado[] a = (Empleado[]) Archivos.leerFichero(dirr);
        boolean key = false;
        for (int i = 0; i < a.length; i++) {
            key = gCodigoID.getText().equals(a[i].getCodigoID());
            if (key) {
                JOptionPane.showMessageDialog(null, "El Código pertenece a otro Empleado");
                break;
            }
        }
        if (!key) {
            if (!((gCodigoID.getText().equals(""))
                    || (gIdentificacion.getText().equals(""))
                    || (gNombre.getText().equals(""))
                    || (gDireccion.getText().equals(""))
                    || (gTelefono.getText().equals(""))
                    || (gSueldo.getText().equals("")))) {
                Empleado nuevo = new Empleado(gCodigoID.getText(), gIdentificacion.getText(), gNombre.getText(), gDireccion.getText(), gTelefono.getText(),
                        Double.parseDouble(gSueldo.getText()));
                Archivos.escribirFichero(dirr, Empleado.agregarEmpleado(a, nuevo));
                JOptionPane.showMessageDialog(null, "AGREGADO CON ÉXITO!");
            }
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        gCodigoID.setText("");
        gIdentificacion.setText("");
        gNombre.setText("");
        gDireccion.setText("");
        gTelefono.setText("");
        gSueldo.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        Empleado[] a = (Empleado[]) Archivos.leerFichero(dirr);
        Empleado nuevo = Empleado.buscarEmpleado(a, gCodigoID.getText());
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "EMPLEADO NO ENCONTRADO!");
        } else {
            gCodigoID.setText(nuevo.getCodigoID());
            gIdentificacion.setText(nuevo.getIdentificacion());
            gNombre.setText(nuevo.getNombre());
            gDireccion.setText(nuevo.getDireccion());
            gTelefono.setText(nuevo.getTelefono());
            gSueldo.setText("" + nuevo.getSueldo());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        Empleado[] a = (Empleado[]) Archivos.leerFichero(dirr);
        Empleado nuevo = Empleado.buscarEmpleado(a, gCodigoID.getText());
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "El Empleado a Eliminar NO EXISTE");
        } else {
            Empleado[] b = Empleado.eliminarEmpleado(a, gCodigoID.getText());
            Archivos.escribirFichero(dirr, b);
            JOptionPane.showMessageDialog(null, "ELIMINADO CON ÉXITO!");
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void gCodigoIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gCodigoIDKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gCodigoID.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gCodigoIDKeyTyped

    private void gIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gIdentificacionKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gIdentificacion.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gIdentificacionKeyTyped

    private void gNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gNombreKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if ((key < 'a' || key > 'z') && (key < 'A' || key > 'Z') && (key != ' ')) {
            evt.consume();
        }
        if (gNombre.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gNombreKeyTyped

    private void gTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gTelefonoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gTelefono.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gTelefonoKeyTyped

    private void gSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gSueldoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if ((key < '0' || key > '9') && (key != '.')) {
            evt.consume();
        }
        if (gSueldo.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gSueldoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField gCodigoID;
    private javax.swing.JTextField gDireccion;
    private javax.swing.JTextField gIdentificacion;
    private javax.swing.JTextField gNombre;
    private javax.swing.JTextField gSueldo;
    private javax.swing.JTextField gTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
