package Ventanas;

import javax.swing.JOptionPane;
import proveeduria_empresa_v3.*;
/**
 *
 * @author Grupo D, S.I. - 001 
 */
public class AddKardex extends javax.swing.JFrame {

    /**
     * Creates new form AddKardex
     */
    public String dirr = "Kardex.txt";

    public AddKardex() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gFecha = new javax.swing.JTextField();
        gNumeroAdquisicion = new javax.swing.JTextField();
        gPrecio = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botoAtualizar = new javax.swing.JButton();
        gCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gTransaccion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Kardex");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nº Productos:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de transaccion:");

        gFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gFechaActionPerformed(evt);
            }
        });
        gFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gFechaKeyTyped(evt);
            }
        });

        gNumeroAdquisicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gNumeroAdquisicionActionPerformed(evt);
            }
        });
        gNumeroAdquisicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gNumeroAdquisicionKeyTyped(evt);
            }
        });

        gPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPrecioActionPerformed(evt);
            }
        });
        gPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gPrecioKeyTyped(evt);
            }
        });

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compartimiento.png"))); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar-el-polvo.png"))); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-atras.png"))); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        botoAtualizar.setText("Actualizar");
        botoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAtualizarActionPerformed(evt);
            }
        });

        gCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gCodigoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Codigo:");

        gTransaccion.setText("Ingreso");
        gTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTransaccionActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(gPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(gNumeroAdquisicion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(gCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(gTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(botonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gNumeroAdquisicion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(gTransaccion))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gFechaActionPerformed

    private void gNumeroAdquisicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gNumeroAdquisicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gNumeroAdquisicionActionPerformed

    private void gPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gPrecioActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        new VenKardex().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        Kardex[] a = (Kardex[]) Archivos.leerFichero(dirr);
        boolean key = false;
        for (int i = 0; i < a.length; i++) {
            key = gCodigo.getText().equals(a[i].getCode());
            if (key) {
                JOptionPane.showMessageDialog(null, "El código ya pertenece a un Producto");
                break;
            }
        }
        if (!key) {
            if (!((gCodigo.getText().equals(""))
                    || (gFecha.getText().equals(""))
                    || (gPrecio.getText().equals(""))
                    || (gNumeroAdquisicion.getText().equals(""))
                    || (gTransaccion.getText().equals("")))) {
                Kardex nuevo = new Kardex(gCodigo.getText(), gFecha.getText(), Integer.parseInt(gNumeroAdquisicion.getText()),
                        Double.parseDouble(gPrecio.getText()), gTransaccion.getText());
                Archivos.escribirFichero(dirr, Kardex.agregarKardex(a, nuevo));
                JOptionPane.showMessageDialog(null, "AGREGADO CON ÉXITO!");
            }
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        Kardex[] a = (Kardex[]) Archivos.leerFichero(dirr);
        boolean key = gCodigo.getText().equals("");
        Kardex nuevo = Kardex.buscarKardex(a, (key) ? "" + 0 : gCodigo.getText());
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "KARDEX no encontrado");
        } else {
            gFecha.setText(nuevo.getFecha());
            gCodigo.setText("" + nuevo.getCode());
            gPrecio.setText("" + nuevo.getPrecioCompra());
            gTransaccion.setText(nuevo.getTipoTrans());
            gNumeroAdquisicion.setText("" + nuevo.getNumeroProdAdq());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        Kardex[] a = (Kardex[]) Archivos.leerFichero(dirr);
        boolean key = gCodigo.getText().equals("");
        Kardex nuevo = Kardex.buscarKardex(a, (key) ? "" + 0 : gCodigo.getText());
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "El Kardex a eliminar NO EXISTE!");
        } else {
            Kardex[] b = Kardex.eliminarKardex(a, (key) ? "" + 0 : gCodigo.getText());
            Archivos.escribirFichero(dirr, b);
            JOptionPane.showMessageDialog(null, "ELIMINADO CON ÉXITO!");
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        gFecha.setText("");
        gCodigo.setText("");
        gPrecio.setText("");
        gTransaccion.setText("");
        gNumeroAdquisicion.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAtualizarActionPerformed
        // TODO add your handling code here:
        Kardex[] a = (Kardex[]) Archivos.leerFichero(dirr);

        boolean key = gCodigo.getText().equals("");

        Kardex nuevo = Kardex.buscarKardex(a, (key) ? "" + 0 : gCodigo.getText());
        if (nuevo == null) {

            JOptionPane.showMessageDialog(null, "KARDEX NO ENCONTRADO");
        } else {
            if (!((gCodigo.getText().equals(""))
                    || (gFecha.getText().equals(""))
                    || (gPrecio.getText().equals(""))
                    || (gNumeroAdquisicion.getText().equals(""))
                    || (gTransaccion.getText().equals("")))) {
                Kardex[] b = Kardex.eliminarKardex(a, gCodigo.getText());
                Kardex[] c = Kardex.agregarKardex(b,
                        new Kardex(gCodigo.getText(), gFecha.getText(), Integer.parseInt(gNumeroAdquisicion.getText()),
                                Double.parseDouble(gPrecio.getText()), gTransaccion.getText()));
                JOptionPane.showMessageDialog(null, "ACTUALILZADO CON ÉXITO");
            } else {
                JOptionPane.showMessageDialog(null, "CAMPOS VACÍOS, NO SE PUEDE ACTUALIZAR");
            }

        }
    }//GEN-LAST:event_botoAtualizarActionPerformed

    private void gCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gCodigoKeyTyped
        // TODO add your handling code here:
char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gCodigo.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gCodigoKeyTyped

    private void gFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gFechaKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if ((key < '0' || key > '9') && (key != '/')) {
            evt.consume();
        }
        if (gFecha.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_gFechaKeyTyped

    private void gNumeroAdquisicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gNumeroAdquisicionKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gNumeroAdquisicion.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gNumeroAdquisicionKeyTyped

    private void gPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gPrecioKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if ((key < '0' || key > '9') && (key != '.')) {
            evt.consume();
        }
        if (gPrecio.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gPrecioKeyTyped

    private void gTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTransaccionActionPerformed
        if (gTransaccion.getText().equals("Ingreso")) {
            gTransaccion.setText("Egreso");
        } else {
            gTransaccion.setText("Ingreso");
        }

    }//GEN-LAST:event_gTransaccionActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddKardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddKardex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoAtualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField gCodigo;
    private javax.swing.JTextField gFecha;
    private javax.swing.JTextField gNumeroAdquisicion;
    private javax.swing.JTextField gPrecio;
    private javax.swing.JButton gTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
