package Ventanas;

import javax.swing.JOptionPane;
import proveeduria_empresa_v3.Proveedores;
import proveeduria_empresa_v3.Archivos;
/**
 *
 * @author Grupo D, S.I. - 001 
 */
public class AddProveedores extends javax.swing.JFrame {

    public String dirr = "Proveedores.txt";

    /**
     * Creates new form AddProveduras
     */
    public AddProveedores() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gIdentificacion = new javax.swing.JTextField();
        gNombre = new javax.swing.JTextField();
        gTelefono = new javax.swing.JTextField();
        gDireccion = new javax.swing.JTextField();
        gEmail = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Proveedores");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Identificacion:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Direccion:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email:");

        gIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gIdentificacionActionPerformed(evt);
            }
        });
        gIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gIdentificacionKeyTyped(evt);
            }
        });

        gNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gNombreActionPerformed(evt);
            }
        });
        gNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gNombreKeyTyped(evt);
            }
        });

        gTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTelefonoActionPerformed(evt);
            }
        });
        gTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gTelefonoKeyTyped(evt);
            }
        });

        gDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDireccionActionPerformed(evt);
            }
        });
        gDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gDireccionKeyTyped(evt);
            }
        });

        gEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gEmailActionPerformed(evt);
            }
        });

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compartimiento.png"))); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar-el-polvo.png"))); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-atras.png"))); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(gEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(75, 75, 75))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gIdentificacionActionPerformed

    private void gNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gNombreActionPerformed

    private void gTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gTelefonoActionPerformed

    private void gDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gDireccionActionPerformed

    private void gEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gEmailActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        Proveedores[] a = (Proveedores[]) Archivos.leerFichero(dirr);
        Proveedores nuevo = Proveedores.buscarProveedores(a, gIdentificacion.getText());
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "No se encontro el Proveedor a eliminar");
        } else {
            Proveedores[] b = Proveedores.eliminarProveedores(a, gIdentificacion.getText());
            Archivos.escribirFichero(dirr, b);
            JOptionPane.showMessageDialog(null, "Se elimino con exito");
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        Proveedores[] a = (Proveedores[]) Archivos.leerFichero(dirr);
        boolean key = false;
        for (int i = 0; i < a.length; i++) {
            key = gIdentificacion.getText().equals(a[i].getIdentificacion());
            if (key) {
                JOptionPane.showMessageDialog(null, "Un Proveedor posse esta identificación");
                break;
            }
        }
        if (!key) {
            if (!((gIdentificacion.getText().equals(""))
                    || (gNombre.getText().equals(""))
                    || (gDireccion.getText().equals(""))
                    || (gTelefono.getText().equals(""))
                    || (gEmail.getText().equals("")))) {

                Proveedores nuevo = new Proveedores(gIdentificacion.getText(), gNombre.getText(),
                        gDireccion.getText(), gTelefono.getText(), gEmail.getText());
                Archivos.escribirFichero(dirr, Proveedores.agregarProveedores(a, nuevo));
                JOptionPane.showMessageDialog(null, "Se agrego con exito");
            }
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        new VenProveedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        gIdentificacion.setText("");
        gNombre.setText("");
        gDireccion.setText("");
        gTelefono.setText("");
        gEmail.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        Proveedores[] a = (Proveedores[]) Archivos.leerFichero(dirr);
        Proveedores nuevo = Proveedores.buscarProveedores(a, gIdentificacion.getText());
        if (nuevo == null) {
            JOptionPane.showMessageDialog(null, "No se encontro el Proveedor");
        } else {
            gIdentificacion.setText(nuevo.getIdentificacion());
            gNombre.setText(nuevo.getNombre());
            gDireccion.setText(nuevo.getDireccion());
            gTelefono.setText("" + nuevo.getTelefono());
            gEmail.setText("" + nuevo.getEmail());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        Proveedores[] a = (Proveedores[]) Archivos.leerFichero(dirr);
        Proveedores nuevo = Proveedores.buscarProveedores(a, gIdentificacion.getText());
        if (nuevo == null) {

            JOptionPane.showMessageDialog(null, "No se encontro el Proveedor");
        } else {
            if (!((gIdentificacion.getText().equals(""))
                    || (gNombre.getText().equals(""))
                    || (gDireccion.getText().equals(""))
                    || (gTelefono.getText().equals(""))
                    || (gEmail.getText().equals("")))) {
                Proveedores[] b = Proveedores.eliminarProveedores(a, gIdentificacion.getText());
                Proveedores[] c = Proveedores.agregarProveedores(b,
                        new Proveedores(gIdentificacion.getText(), gNombre.getText(),
                                gDireccion.getText(), gTelefono.getText(), gEmail.getText()));
                Archivos.escribirFichero(dirr, c);
                JOptionPane.showMessageDialog(null, "Se Actualizo con exito");
            } else {
                JOptionPane.showMessageDialog(null, "NO se puede Actualizar Campos Vacios");
            }

        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void gIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gIdentificacionKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gIdentificacion.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gIdentificacionKeyTyped

    private void gNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gNombreKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if ((key < 'a' || key > 'z') && (key < 'A' || key > 'Z') && (key != ' ')) {
            evt.consume();
        }
        if (gNombre.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gNombreKeyTyped

    private void gDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gDireccionKeyTyped

    private void gTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gTelefonoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (key < '0' || key > '9') {
            evt.consume();
        }
        if (gTelefono.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_gTelefonoKeyTyped

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField gDireccion;
    private javax.swing.JTextField gEmail;
    private javax.swing.JTextField gIdentificacion;
    private javax.swing.JTextField gNombre;
    private javax.swing.JTextField gTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
